### PR TITLE
Adriana/katas

### PR DESCRIPTION
**Pull request by AdriOli134**

### CODE REVIEW

**Review by J0c4 — CHANGES_REQUESTED** [review]
Hi @AdriOli134 , the target branch in this PR is wrong, it should be dev/katas instead of main, please update the PR to point the correct branch so the files with your changes are the only ones displayed as part of this PR

**Comment by AdriOli134** [comment]
Hi @J0c4 How can  I solve this?. Maybe this problem is because I  had a merge error and did merge adriana/katas into a dev/katas

**Comment by J0c4** [comment]
Hi @AdriOli134 , just noticed what you mention about the merge of adriana/katas into dev/katas. You can either create your branch from scratch or you can checkout to the commit before that merge commit happened, then do the merge of dev/katas into adriana/katas.

**Comment by J0c4** [comment]
Clarification to my previous comment, for the option where you can checkout to the commit before the merge commit, after you checkout, create a new branch (say, adriana/katas2), and then, do the merge of dev/katas into adriana/katas. Then, you fix any checkstyle issue in that new branch and push it to create a new PR that points to dev/katas. If you go with that option, you can close this PR and delete the old branch

**Pull request closed without merging**
