### PR TITLE
Rene's katas solutions with checkStyles

### PR DESCRIPTION
**Pull request by Renucopata**

### CODE REVIEW

**Review by J0c4 — DISMISSED** [review]
Hello @Renucopata , good work, however, unit tests are missing, thus, kata is incomplete. We can merge as is, but you need to show progress on this area, otherwise, it will affect your performance at the end of the course. Keep practicing

**Comment by J0c4** [comment]
Please fix conflicts so we can merge this.

Since we have met deadline, please push only merge commit for solving conflicts. Any other change will be rejected

**Comment by Renucopata** [comment]
Hi @J0c4 I added the unit tests for all the katas with the checkstyles corrections

**Comment by J0c4** [comment]
> Please fix conflicts so we can merge this.
> 
> Since we have met deadline, please push only merge commit for solving conflicts. Any other change will be rejected

Hi @Renucopata , as stated, we cannot merge changes that were added after deadline, so in order to follow this, please revert commits added today related to unit tests. We are expecting to solve the conflicts in this PR with changes we had until last night (deadline) and then we can merge.

Please consider that today we will merge all, so we will have to left this PR behind and close it if we cannot merge it today

**Pull request closed without merging**
