### PR TITLE
building and running checkstyle for each file

### PR DESCRIPTION
**Pull request by HugoS922**

### CODE REVIEW

**Review by J0c4 — CHANGES_REQUESTED** [review]
Hello @HugoS922 , there are a lot of unexpected files added in this PR (.gitattributes, .gitignore, App.java, gradle files, etc). I'd suggest to start over and just add the correct files with your code, we cannot merge this PR as is

**Comment by J0c4** [comment]
Hi @HugoS922 , thanks for the updates. Still, the problem of unexpected file still present, this prevents this PR to be merged because adding those files could cause issues, please solve before I can review them and approve.

Also, let me know in case you are planning to add unit tests in a separate PR

**Review by HugoS922 — COMMENTED** [review]
deleting unexpected files

**Review by J0c4 — APPROVED** [review]
Hi @HugoS922 , code looks good, but tests are missing, so kata is incomplete. Still, we can merge as is, good work on solving the initial issues that this PR has. Please practice unit tests, if we don't see progress on this, it can affect your performance results of the course.

**Pull request merged**
