### PR TITLE
Libertad/spaceinvaders Add unit test for Shield and Board class

### LINKED ISSUE #143: Create Blocks and Shields

### PR DESCRIPTION
**Pull request by TolabaLib**
Add unit test for Shield and Board class

### CODE REVIEW

**Comment by junior0123** [comment]
Good Job! :D

**Review by junior0123 — APPROVED** [review]

**Review by RodrigoValda — APPROVED** [review]
Nice job

**Comment by RodrigoValda** [comment]
Nice job with the unit tests

**Review by Solrac1906 — APPROVED** [review]
Good job

**Pull request merged**
